workflows:
  ios-workflow:
    name: Build and release iOS app
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_ID: com.hootowl.govpulse
        APP_NAME: GovPulse
    scripts:
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.ipa
    publishing:
      app_store_connect:
        api_key: Encrypted(...) # You'll fill this in from Codemagic UI
